### ISSUE TITLE
hiiii, just a question

### ISSUE THREAD

**Issue by whitelistapp** [FreeStuffBot/website#42]
could you tell me how to set this website up? i get very lost with vue/nuxt and when I start it up it gives me webpack errors, dist doesn't exist despite me generating/building it and mismatching vue versions with vue compiler.

**Comment by maanex** [comment]
Hi, we're not providing support for self-hosting this website. We'd also like to remind you to remove all FreeStuff branding as the name, logo and other assets are under copyright. That said you will have to give credit to the creators of this website if you ever plan on building upon this.

**Comment by maanex** [comment]
Hey there. Thanks for banning me from your support server after trying to settle this peacefully. I'm going to interpret this as that there is no intent to comply with what was asked of you so I'll have to take action now. If you wish to talk about it feel free to contact me.

https://media.discordapp.net/attachments/1072594653448245279/1120107961575030784/image.png

**Comment by maanex** [comment]
cc @whitelistapp
